### ISSUE TITLE
Il manque les leçons 29 à 50

### ISSUE THREAD

**Issue by Quezako** [apommel/minna-no-nihongo#1]
Bonjour Aurélien,

Tout d'abord, félicitation pour votre travail, c'est un outil intéressant pour apprendre le japonais et python !

Toutefois, j'ai un problème : il semble manquer les leçons 29 à 50.
Or, j'en suis rendu à la leçon 40 et j'aurais bien besoin de ton outil et de ta BDD pour progresser.

Bonne continuation !

**Comment by apommel** [comment]
Bonjour, merci pour votre retour.

Les leçons 29 à 50 n'ont en effet jamais été ajoutées : c'était en effet un processus assez lourd, et je suis ensuite passé à d'autres outils plus standards et moins limités. Si vous le souhaitez, vous pouvez ajouter les nouvelles leçons manuellement et je les ajouterai sur la base de donnée en ligne.
Néanmoins, je vous conseille plutôt de prendre en main un outil comme Anki, ainsi qu'un deck créé par la communauté (celui-ci par exemple : https://ankiweb.net/shared/info/916720354). Ce projet est plutôt présent en ligne à des fins d'archivage, car les alternatives comme Anki sont bien plus puissantes et développées.

**Comment by Quezako** [comment]
Tout à fait ! 
En fait, j'utilise justement ce deck Anki, mais il comporte pas mal de fautes, surtout sur le 2e livre.
Je cherchais du coup les définitions officielles, car certains mots avec la même sonorité n'ont pas la bonne définition.
J'ai récupéré la liste intégrale en anglais de Paul Denisowski, ça me donne déjà une indication.

Je suis en train de préparer une version plus complète :
- focalisé sur l'audio : écoute et prononciation des mots et des phrases en japonais.
- adapté pour le TTS (text-to-speech), si le mp3 est manquant ou de mauvaise qualité.
- phrases plus simples et plus adaptées au niveau de la leçon ou du livre en cours (N4 maximum).
- cartes mal traduites ou traduites aproximativement
- cartes en double
- qualification des tous les mots avec le niveau JLPT, même les communs
- isolation des mots N3+ dans L51
- ajout d'images, pour se focaliser sur le contexte et se passer au maximum de la langue française dans le processus d'apprentissage.

Un premier jet avec le premier livre :
https://ankiweb.net/shared/info/1419539410

**Comment by apommel** [comment]
Une très bonne initiative ! Bon courage. Pour obtenir les définitions exactes en Français, la meilleure solution serait en effet d'acheter la traduction française officielle. Je n'ai de mon côté plus accès à plus de définitions que ce que j'avais déjà ajouté en 2017 donc je ne peux pas plus vous aider pour ça.
